### ISSUE TITLE
API Key exposed

### ISSUE THREAD

**Issue by titurius** [hy00un/mal-crawler-GUI#1]
Nice project. You probably don't want to expose your personal API key here, right? 

https://github.com/hy00un/mal-crawler-GUI/blob/f24b1aa100b501e794ba02ea551cc11aad4ef634/crawler.py#L34

Maybe you can put the API keys and URLs into a configuration file and only publish example data.

**Comment by hy00un** [comment]
oh.. Thank you for your comment :)
